version: '3'

services:
  artstudioapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: artstudio-docker
    container_name: artstudioapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/artstudio
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/artstudio

  db:
    image: mongo:5
    container_name: mongo-artstudio
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-artstudio
    volumes:
      - ./mongo:/data/db